# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
    name: {{ include "name" . }}
    namespace: {{ .Release.Namespace }}
labels:
    app.kubernetes.io/name: {{ include "name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
    maxUnavailable: 1
{{- if semverCompare ">= 1.26-0" .Capabilities.KubeVersion.Version }}
    unhealthyPodEvictionPolicy: AlwaysAllow
{{- end }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ include "name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
