# SPDX-FileCopyrightText: 2024 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

{{- if gt (int .Values.replicaCount) 1 }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "name" . | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
{{- if not (kindIs "invalid" .Values.resilience.pdb.maxUnavailable) }}
    maxUnavailable: {{ toYaml .Values.resilience.pdb.maxUnavailable }}
{{- end }}
{{- if not (kindIs "invalid" .Values.resilience.pdb.minAvailable) }}
    minAvailable: {{ toYaml .Values.resilience.pdb.minAvailable }}
{{- end }}
{{- if .Values.resilience.pdb.unhealthyPodEvictionPolicy }}
    unhealthyPodEvictionPolicy: {{ .Values.resilience.pdb.unhealthyPodEvictionPolicy | quote }}
{{- end }}
    selector:
      matchLabels:
          app.kubernetes.io/name: {{ include "name" . | quote }}
{{- end }}
