version = 1
SPDX-PackageName = "Gardener service-account-issuer-discovery"
SPDX-PackageSupplier = "The Gardener project <gardener@googlegroups.com>"
SPDX-PackageDownloadLocation = "https://github.com/gardener/service-account-issuer-discovery"

[[annotations]]
path = [".ci/**", ".github/**", ".gitignore", "charts/service-account-issuer-discovery/.helmignore", "charts/service-account-issuer-discovery/templates/_helpers.tpl", "CODEOWNERS", "go.mod", "go.sum", "VERSION"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = ["CONTRIBUTING.md", "README.md"]
precedence = "aggregate"
SPDX-FileCopyrightText = "2022 SAP SE or an SAP affiliate company and Gardener contributors"
SPDX-License-Identifier = "CC-BY-4.0"
