#!/usr/bin/env bash

# SPDX-FileCopyrightText: 2022 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

# For the check step concourse will set the following environment variables:
# SOURCE_PATH - path to component repository root directory.

export SOURCE_PATH="$(readlink -f "${BASH_SOURCE[0]}/..")"

cd "${SOURCE_PATH}"

go install github.com/securego/gosec/v2/cmd/gosec@v2.22.11

make verify sast-report

curl -s "https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3" | bash -s -- --version 'v3.5.4'

echo "> Lint helm charts"
make helm-lint
